### ISSUE TITLE
MySQL date types are returned as NULL

### ISSUE THREAD

**Issue by shanezilla** [qutheory/mysql#13]
Data returned as a result from an SQL select statement contains MySQL.Value.null for any fields of type DATE or TIME. 

Inserting data into the db using a formatted date string as the value for a date field, using .string() in the appropriate prepared statement values, works just fine. But getting that data back out of the db results in MySQL.Value.null for those fields.

**Comment by tannernelson** [comment]
Thanks for reporting, this should be a relatively easy fix. (possibly you want to try your hand?)

**Comment by tannernelson** [comment]
This should be fixed in 0.3.1.
