### ISSUE TITLE
Unable to invoke subcommands

### ISSUE THREAD

**Issue by faklyasgyuri** [qutheory/mysql#15]
Hi!
I followed your installation guide, installed and link successfully mysql, etc. But after I run this command> swift build -Xswiftc -I/usr/local/include/mysql -Xlinker -L/usr/local/lib 
I get the following error message > error: unable to invoke subcommand: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build (No such file or directory)
How can I solve this problem or what did I in a wrong way? My xCode Verision is> Version 7.3.1 (7D1014) and I installed Swift June 20, 2016 development snapshot.
Thanks

**Comment by tannernelson** [comment]
That means you are using Swift 2. 

I made a tutorial here for getting started with Vapor, it would help with this package, too.

https://www.youtube.com/watch?v=YxvQo-EH2AA
