### ISSUE TITLE
Xcode build settings

### ISSUE THREAD

**Issue by bspringston** [qutheory/mysql#6]
It would help out if documentation explained how to set the build settings to run the from inside Xcode.  In Xcode, under Basic build settings, set "Header Search Paths" to /usr/local/include/mysql and set "Library Search Paths" to /usr/local/lib.

**Comment by tannernelson** [comment]
Oh I forgot to include that!

You can run this to generate the project with that already added:

```
swift package generate-xcodeproj -Xlinker -L/usr/local/lib/
```

If it also complains about header paths, you can add those with `-Xswiftc` and `-I/usr/local/include/mysql`

Let me know if any of those work for you and we can add to the docs. My computer has a million different versions of MySQL installed so it's hard to tell what will work if you only install through brew.

**Comment by bspringston** [comment]
This didn't work for me.  I still have to manually add the build settings in Xcode after generating the Xcode project

**Comment by tannernelson** [comment]
If you use the [Vapor Toolbox](https://github.com/qutheory/vapor-toolbox) you can do `vapor xcode --mysql`
