### ISSUE TITLE
value enum convenience accessors

### ISSUE THREAD

**Issue by collinhundley** [qutheory/mysql#7]
What's the reasoning behind the use of enum `Value` here vs. protocol `Value` [in Fluent](https://github.com/qutheory/fluent/blob/master/Sources/Fluent/Model/Value.swift)?

Parsing database results returned as enums is a pain - do I really have to `switch` on every entry in order to bind a variable to the correct type, or is there a better way to handle this?

Example: 

```swift
let results = try mysql.execute("SELECT name FROM user")
let entry = results[0]
if let name = entry["name"] {
    switch name {
        case let .string(myName):
            // Finally we have our property as a String
            ...
        default:
            ...
    }
}
// And we repeat for every property fetched
```

**Comment by tannernelson** [comment]
You can add an extension to make casting easier. This should probably be included in the main repo.

Like this:
```extension Value {
public var string: String? { // do the switch in here }
}```

This library wasn't really meant to be directly accessed by end users. Hopefully there would be an ORM or some other convenience layer in between (as in the case of Fluent). For that reason, I didn't prioritize convenience accessors.
